backend:
  name: github
  repo: afa-santateresa/afa-santateresa.github.io
  branch: main
  base_url: https://afa-auth.fly.dev/

media_folder: static/imgs
public_folder: assets/imgs

collections:
  - name: "pagina"
    label: "Pàgina"
    folder: "src/pagines"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tipus", name: "layout", widget: "hidden", default: "layouts/default.njk"}
      - {label: "Descripció", name: "descripcio", widget: "text"}
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Adreça", name: "permalink", widget: "string"}
      - {label: "Actualitzat", name: "actualitzat", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD"}
      - {label: "Versió", name: "versio", widget: "number", default: 1, value_type: "int"}
      - {label: "Contingut", name: "body", widget: "markdown"}

  - name: "documents"
    label: "Documents"
    files:
      - name: "documents"
        label: "Documents de l'AFA"
        file: "src/_data/documents.yaml"
        fields:
          - label: "Cursos"
            name: "items"
            widget: "list"
            fields:
              - {label: "Curs", name: "curs", widget: "string"}
              - label: "Documents"
                name: "documents"
                widget: "list"
                fields:
                  - {label: "Tipus", name: "tipus", widget: "select", options: ["acta junta", "acta assemblea", "acta", "resum consell", "memòria", "document", "altres"]}
                  - {label: "Data", name: "data", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD"}
                  - {label: "Títol", name: "titol", widget: "string"}
                  - {label: "URL o fitxer", name: "url", widget: "file", media_folder: "/static/docs", public_folder: "/assets/docs"}

  - name: "noticia"
    label: "Notícia curs 25-26"
    folder: "src/noticies/25-26"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tipus", name: "layout", widget: "hidden", default: "layouts/default.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "post"}
      - {label: "Curs", name: "curs", widget: "hidden", default: "25-26"}
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD"}
      - {label: "Imatge", name: "image", widget: "image", required: false}
      - {label: "Fitxer", name: "fitxer", widget: "file", required: false, media_folder: "/static/docs", public_folder: "/assets/docs"}
      - {label: "Versió", name: "versio", widget: "number", default: 1, value_type: "int"}
      - {label: "Contingut", name: "body", widget: "markdown"}
